Numpy 
1. Numpy array have a fixed size at creation
2. Created in C language
3. Similar data and requires a list

In [4]:
# creating a numpy

import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,0])
print(a)
print(type(a))

[1 2 3 4 5 6 7 8 9 0]
<class 'numpy.ndarray'>


In [5]:
# 1D array aka vector
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [6]:
# arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [8]:
# with reshape (super important)

np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
# 3*3 reshape

np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# np.ones and np.zeros

np.ones((2,2))
print('------------')
np.zeros((2,2))

------------


array([[0., 0.],
       [0., 0.]])

In [13]:
# linsapce -- it takes 3 input(lower range, upper range and number of item)
np.linspace(-10,10,30)

array([-10.        ,  -9.31034483,  -8.62068966,  -7.93103448,
        -7.24137931,  -6.55172414,  -5.86206897,  -5.17241379,
        -4.48275862,  -3.79310345,  -3.10344828,  -2.4137931 ,
        -1.72413793,  -1.03448276,  -0.34482759,   0.34482759,
         1.03448276,   1.72413793,   2.4137931 ,   3.10344828,
         3.79310345,   4.48275862,   5.17241379,   5.86206897,
         6.55172414,   7.24137931,   7.93103448,   8.62068966,
         9.31034483,  10.        ])

In [14]:
# np.identity-- used to create an identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.identity(12)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [26]:
import numpy as np

# 0D array (scalar)
a = np.array(10)

# 2D array (2 rows, 5 columns → 10 elements)
b = np.arange(1, 11, dtype=float).reshape(2, 5)

# 3D array (2 × 2 × 2 → 8 elements needed)
c = np.arange(1, 9).reshape(2, 2, 2)

print("Array a:")
print(a)
print("Shape:", a.shape)
print("Dimensions:", a.ndim)
print("Size",a.size)
print("Item Size:", a.itemsize)

print("\nArray b:")
print(b)
print("Shape:", b.shape)
print("Dimensions:", b.ndim)
print("Size",b.size)
print("Item Size:", b.itemsize)

print("\nArray c:")
print(c)
print("Shape:", c.shape)
print("Dimensions:", c.ndim)
print("Size:",c.size)
print("Item Size:", c.itemsize)



Array a:
10
Shape: ()
Dimensions: 0
Size 1
Item Size: 8

Array b:
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
Shape: (2, 5)
Dimensions: 2
Size 10
Item Size: 8

Array c:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Dimensions: 3
Size: 8
Item Size: 8


In [3]:
import numpy as np
print(np.__version__)

2.4.2


In [4]:
my_list = [1,2,3,4]
my_list = my_list * 2
print(my_list)
print(type(my_list))

[1, 2, 3, 4, 1, 2, 3, 4]
<class 'list'>


In [5]:
my_list = np.array([1,2,3,4])
my_list = my_list * 2
print(my_list)
print(type(my_list))

[2 4 6 8]
<class 'numpy.ndarray'>


Slicing


In [7]:
# 2D array

array= np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16]])
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [10]:
# slicing
print(array[0:2:2])

[[1 2 3 4]]


In [11]:
# column seletction
print(array[:,0])

[ 1  5  9 13]


In [14]:
 # min, max, sum, prod
a = [[1,2,3],
    [4,5,6],
    [7,8,9]]
print(np.max(a,axis= 1))

[3 6 9]


In [22]:
import numpy as np

a1 = np.arange(12).reshape(3,4)
print(a1)
print('-----------')
a2 = np.arange(16).reshape(4,4)
print(a2)
print('-----------')
dot = np.dot(a1, a2)
print(dot)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-----------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
-----------
[[ 56  62  68  74]
 [152 174 196 218]
 [248 286 324 362]]


In [23]:
mat1 = np.arange(24).reshape(6,4)
mat1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Fancy Indexing

In [24]:
mat1[[0,1,3,5]]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [26]:
a = np.random.randint(1,100,50).reshape(10,5)
print(a)

[[76 24 25 18 69]
 [84 27 37 85 49]
 [72 96 44 64  9]
 [49 29 13 73 42]
 [65 93 58 48 59]
 [64 58 62 28 15]
 [70 73 59 40 84]
 [ 5 26 34  2 87]
 [98 89 58 84 84]
 [42 42 92 33 94]]


In [27]:
# boolan indexing

a[a>60]

array([76, 69, 84, 85, 72, 96, 64, 73, 65, 93, 64, 62, 70, 73, 84, 87, 98,
       89, 84, 84, 92, 94], dtype=int32)

Broadcasting

In [37]:
a = np.arange(12).reshape(4,3)
b = np.arange(3)
print(a)
print('==================')
print(b)
print('==================')
print(a + b)

# a = np.arange(12).reshape(3,4)
# b = np.arange(3)
# print(a)
# print('==================')
# print(b)
# print('==================')
# print(a + b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]
