In [1]:
import numpy as np


np.sort

In [4]:
a = np.random.randint(1,100,24)
a

array([40, 45, 90, 80, 49, 93, 39, 75, 20, 52, 29, 47, 33, 88, 40, 45, 11,
       98, 22, 49, 42, 82, 45, 87], dtype=int32)

In [10]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[ 5, 67,  3, 35],
       [24, 71, 26, 62],
       [97, 37, 70, 50],
       [41, 12, 87, 29],
       [41, 56,  7, 52],
       [45, 26, 33, 96]], dtype=int32)

In [14]:
np.sort(b,axis=0)

array([[ 5, 12,  3, 29],
       [24, 26,  7, 35],
       [41, 37, 26, 50],
       [41, 56, 33, 52],
       [45, 67, 70, 62],
       [97, 71, 87, 96]], dtype=int32)

In [15]:
mat1 = np.arange(12).reshape(4,3)

In [16]:
mat1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
np.argmax(mat1)

np.int64(11)

cumsum

In [18]:
np.cumsum(mat1)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66])

np.percentile

In [20]:
np.percentile(a,100)

np.float64(98.0)

In [25]:
mat2 = np.array([10,20,30,40,50])
mat2

array([10, 20, 30, 40, 50])

In [26]:
np.percentile(mat2, 30)

np.float64(22.0)

Clipping

In [32]:
import numpy as np

mat3 = np.random.randint(1,200,100)
print(mat3)

print('================================')

mat3 = np.clip(mat3, 45, 175)

print(mat3)


[ 52 175  50  76 179 196 165  99  60  51  32 184  84 193  89 153   7 120
  81  26  36 109 176   9 127  44   5 120  56 152 141  93  48  72  20  67
 104  44 190 121   3  62 119 184 107 129  36  28  93  22  28 190 138 135
  47  43  44 147 126  20 142  93 145 143 126  66  39  15 133 114  50 114
 167  93  46 115  84 170  69  99  96  14 198  32  22  52 115 188 159  40
 137 192 185 190  84 187 194 101 155 112]
[ 52 175  50  76 175 175 165  99  60  51  45 175  84 175  89 153  45 120
  81  45  45 109 175  45 127  45  45 120  56 152 141  93  48  72  45  67
 104  45 175 121  45  62 119 175 107 129  45  45  93  45  45 175 138 135
  47  45  45 147 126  45 142  93 145 143 126  66  45  45 133 114  50 114
 167  93  46 115  84 170  69  99  96  45 175  45  45  52 115 175 159  45
 137 175 175 175  84 175 175 101 155 112]
